
name: reflex_button
description: A Flutter package that provides customizable, animated reflex buttons.
version: 0.0.1
homepage: https://github.com/surerhasan/reflex_button
repository: https://github.com/surerhasan/reflex_button
issue_tracker: https://github.com/surerhasan/reflex_button/issues
environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
